### ISSUE TITLE
Date in subprofile (collection) is always 0000-00-00

### ISSUE THREAD

**Issue by jbreuer** [Arlanet/CopernicaNET#11]
Not sure if it's a bug in CopernicaNET, but I would still like to report it here. When I add a date in profile (database) it just works. When I try to add a date in a subprofile (collection) it's always 0000-00-00. I've checked both [CreateProfile and CreateSubProfile in the data handler](https://github.com/Arlanet/CopernicaNET/blob/179f058dacbadcff3cba174a27279df9c4c42bf5/Src/CopernicaNET/Helpers/CopernicaDataHandler.cs#L31-L39) and the date is in jsondata that is being posted. So maybe it's a bug in Copernica since we just post the date as part of the jsondata.

**Comment by jbreuer** [comment]
There was an issue with having the DateTime property on a model which is passed to Copernica. When serialized to JSON the date was in wrong format. Now I store the value as a string on the model in the format YYYY-MM-DD HH:MM:SS and it works.

**Comment by LennardF1989** [comment]
In order to keep using a DateTime in your model, you can choose to implement a custom converter for Json.NET.

It is stated in the documentation that the default serializer is now the ISO8601 format: http://www.newtonsoft.com/json/help/html/datesinjson.htm - so I suspect that Copernica expects a different format. Hence it returns 0000-00-00.

I'll make a note we have to bundle such a converter with CopernicaNET. Thanks for reporting!

**Comment by jbreuer** [comment]
I tried adding a custom converter, but the CopernicaField attribute already has a JsonFieldsConverter. So that converter should probably be updated to convert the datetime in the correct format. For now I'll just store it as a string on the object.
